### ISSUE TITLE
medsio expects certain fields in meds files

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmixer#10]
Fields such as image_flags should be considered optional

**Comment by esheldon** [comment]
I ran into this when trying to process great3reredux

**Comment by beckermr** [comment]
Right. A few notes.
1. So for great3reredux you need to use `SimpSimMEDSImageIO` and not the SV/Y1 meds readers. This means that in the parameter file, you should specify `imageio_type: "simpsimmeds`. 
2. As I noted before, you will have to change the tag name for finding the psf image from `ind_psf` to `psf_id` in the `SimpSimMEDSImageIO` class. 
3. Also, you need to feed the psf fits file to the code on the command line. It should look something like this

``` shell
#!/bin/bash

python -u `which ngmixit` --fof-range=$1,$2 \
       --psf-file=psf_data.fits \
       config.yaml output_data.fits \
       meds_data.fits.fz
```

**Comment by beckermr** [comment]
I am closing this.
