### ISSUE TITLE
logging is not buffered but stdio is

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmixer#14]
The print_pars call is falling out of sync with the logger

I don't know how to send the logger to print_pars

**Comment by beckermr** [comment]
Also need to interface the --verbose option in ngmixit into the logger.

**Comment by beckermr** [comment]
- [X] remove logger
- [x] fix verbose option in ngmixit

**Comment by beckermr** [comment]
This should be fixed. `ngmixit` now only takes a `--verbosity=1` command line switch instead of verbose.
