### ISSUE TITLE
converting checkpoint data to a list

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmixer#15]
Why is this?

``` python
self.data = list(self.data)
```

**Comment by beckermr** [comment]
So that it can be extended/appended to later.

**Comment by esheldon** [comment]
I think this is fine as long as we don't try to process too much data

**Comment by beckermr** [comment]
Worried about memory leaks? I have never had an issue, but now I will. :)

**Comment by esheldon** [comment]
not memory leak per se, just more overall usage if the gc doesn't kick in. anyway, I like the list thing more as I think about it.  It avoids some of the bookkeeping complexities
