### ISSUE TITLE
refactor handling of weight maps

### ISSUE THREAD

**Issue by beckermr** [esheldon/ngmixer#16]
The weight map handling in the MEDS io classes needs to be refactored a bit and cleaned up.

**Comment by beckermr** [comment]
From @esheldon:

> under region=="weight" you have
> 
> ```
> wt_us = wt
> ```
> 
> seems a bit misleading, maybe that should be None?

**Comment by beckermr** [comment]
Note the previous is in `simpsimmedsio.py`

**Comment by esheldon** [comment]
Also monkey patching can be problematic

**Comment by esheldon** [comment]
In simpsimmedsio

```
_get_band_observation(..):
...
obs.weight_us = wt_us
```

The above is what I mean by monkey patching

**Comment by beckermr** [comment]
Yeah totally agree. Just hacking things up so it runs for now. Def need to clean up when the whole thing gets refactored.

**Comment by esheldon** [comment]
Design-wise, not sure if it makes sense to add set_usweight() etc. though.  Maybe this belongs in the meta dictionary, which is explicitly a grab-bag?

**Comment by beckermr** [comment]
Right. So in terms of design, the reason that I am mucking with the weights in the first place is because the MOF expects two weights. The first is for the initial iteration of the fitting and the second is for the subsequent ones. This happens to be uberseg, but actually a more general interface to the MOF should be provided. Something like `initial_weight` and `iter_weight` or whatever.

**Comment by esheldon** [comment]
Maybe a new datastructure is needed, designed for MOF.

This could either take an Observation/Obslist/ etc. on construction or inherit from one of those.

With a new data type you can apply constraints/requirements to make sure you have what you want without resorting to monkey patching Observations.

**Comment by beckermr** [comment]
closing this in favor of #25
