### ISSUE TITLE
incredibly long lines

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmixer#29]
We need a style guide.

These long lines are nearly impossible for me to parse, even when they fit on
my screen.  And they don't fit on my screen often, needing to be wrapped,
making it even more difficult.

I argue this is not bikeshedding, it is actually difficult to read.  This is why
books are carefully typeset so the lines are not too long.

A good general rule is to keep lines to < 80 columns.  

This is easily fixed in most cases by formatting like this

``` python
# long way
x = func(blah, stuff, index=3, very_long_keyword=something.get('thing',None), verbose=True, **kw)

# more readable way
thing = something.get('thing',None)
x = func(blah,
         stuff,
         index=3,
         very_long_keyword=thing,
         verbose=True,
         **kw)
```

Note there is no need for an ending backslash when in between brackets (), so
this is not really extra typing.  We can remove most of the '\' from the code

I am happy to do this in the code as I'm reading through it, trying to understand
your refactor

**Comment by beckermr** [comment]
Sure yeah. I work with 120 char lines generally because my terminal is not from the 80s. :)

**Comment by esheldon** [comment]
120 is just too much for me to parse efficiently.

**Comment by beckermr** [comment]
ok :) 80 is cool too!

**Comment by esheldon** [comment]
For the putting args in different lines, I have my editor set up so it auto-indents to the previous bracket (

**Comment by beckermr** [comment]
Yeah that is great by me.

**Comment by esheldon** [comment]
Other style issues that I think are important to readability and maintainability
1. No inline imports. i.e. imports right in the middle of a code block
2. keep functions as short as _possible_ (but not shorter).  i.e.  factor out large code sections to separate methods.  One guideline is not to have any nesting too deep, say deeper than 3.  If the lines cannot be made less than 80 columns, it is probably too nested.
3. Separate out complex logic into a new function, especially if you have lots of such choices to make.

**Comment by beckermr** [comment]
I am happy with everything in that list. 

FWIW, I tend to write longer functions so that the logic of what is happening appears in a single spot in the file. It makes it tough to track things when you have to flip back and forth between several different 5 line functions to see what is going on. 

Feel free to make changes as you see fit. Maybe don't touch some of the MOF stuff for now. We are still debugging and I know the code pretty well which makes that easier.

**Comment by esheldon** [comment]
Sure, common sense must prevail.  It makes sense to split up logic when you
have a function that has a series of independent, but possibly complex,
logical steps. A couple of examples

``` python
def getflags(self, data):
    """
    this is better than spelling out all these possibly complex
    functions in the same place
    """
    flags = ones(data.size)
    flags |= self.select_flags(data)
    flags |= self.select_mags(data)
    flags |= self.select_mask(data)

    return flags
```

``` python
def measure(self, data):
    """
    better than spelling out each check
    """
    for i in xrange(data.size):
        if not self.check_good(data[i]):
            data['flags'][i] |= NOT_GOOD
            continue
        if not self.check_not_faint(data[i]):
            data['flags'][i] |= NOT_GOOD
            continue
        if not self.check_is_a_galaxy(data[i]):
            data['flags'][i] |= NOT_GALAXY
            continue

        # do something interesting
```

or even better

``` python
def measure(self, data):
    """
    better than spelling out each check
    """
    for i in xrange(data.size):
        data['flags'][i] = self.getflags(data[i])
        if not data['flags'][i]:
            continue

        # do something interesting
```
