### ISSUE TITLE
test fit flagging

### ISSUE THREAD

**Issue by beckermr** [esheldon/ngmixer#4]

**Comment by beckermr** [comment]
It appears that objects with no cutouts (why do these exist, @esheldon?) get flagged as UTTER_FAILURE (which is true of course) and not as NO_CUTOUTS.

**Comment by esheldon** [comment]
This can happen if the bounding box I define for the object in the coadd does not intersect any of the single-epoch images in that band.

If the flag is set to NO_CUTOUTS instead does the logic still propagate correctly?

**Comment by beckermr** [comment]
The logic in the current way the flags are set is wrong, which is why I created this issue.

**Comment by esheldon** [comment]
I mean, if you switch the flags, does the code still bail out and skip this object correctly or is it relying on utter_failure?

**Comment by beckermr** [comment]
ohhh yes, the output is correct. There is a bug where the UTTER_FAILURE flag bit was not imported from default.py, but otherwise it still flags the object as bad, just not for the exactly right reason. This is a minor bug that I am fixing today. I just did not understand it at all.

**Comment by esheldon** [comment]
I think you are saying it should be fine to switch to NO_CUTOUTS, OK

**Comment by beckermr** [comment]
This should be fixed now.

**Comment by beckermr** [comment]
It is still buggy!

**Comment by beckermr** [comment]
This looks to be fixed. Closing, but let's keep any eye on the flags.
