### ISSUE TITLE
switch megamixer to layout runs like before

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmixer#45]
This way I don't have to get the "run" correct in the megamixer file twice, which will definitely get out of sync.

An added bonus:  This way output_dir can even be the same on a given system for every run.

**Comment by esheldon** [comment]
sub-context I forgot to mention:

I want my files to go to

```
/some/long/dir/{run}
```

so my output_dir in the config file would have to look like that.  But currently I'm already setting run: " " so I would have to put it in two places, and I  am bound to forget that

**Comment by beckermr** [comment]
didn't follow this at all

outputs go to {output_dir}/{tilename}

**Comment by esheldon** [comment]
right, this means if I want a unique output directory based on the run I need to had put that into the file by hand.  The most obvious unique output directory would be

```
output_dir:  /some/path/{run}
```

But I already have an entry in the config file for `run:`, so it makes sense to me that the program just does this for me and write files under `{output_dir}/{run}/{tilename}`

Otherwise I have to remember to update both the entry for `run:` and the entry for `output_dir:` every time I make a new run.  Having to put configuration in two different places is bug prone.

**Comment by beckermr** [comment]
ahhh. I always make a new virtualenv for each run (and pull ngmix and ngmixer) so that I have exact copies of the code state when each run is launched.

**Comment by esheldon** [comment]
this isn't about code, it is about the config file and where data gets written

**Comment by beckermr** [comment]
ok. changing this issue to switch to your system. some notes so i get it right would help.

**Comment by esheldon** [comment]
let's just do the simple adding {run} to the path for now

**Comment by beckermr** [comment]
done.
