### ISSUE TITLE
use segmentation map to perform extractorcorrector ?

### ISSUE THREAD

**Issue by keckert7** [esheldon/ngmixer#79]
I'm finding that for the deep fields, there are objects left over after performing the medsextractorcorrector routine. I believe this is because not everything in the postage stamp is linked as a neighbor. To remove all the objects in the postage stamp, I was thinking it could be useful to add an option to use the segmentation map ids to specify the neighboring objects. I've poked around render_ngmix_nbrs.py and extractor_corrector.py to see if this might be possible, but it looks like it could be tricky in the current framework since. I'd like to use as much of the existing architecture as possible, though, so as not to introduce any new bugs.

**Comment by esheldon** [comment]
For the deep fields I modified the original group finder by @beckermr to link fewer things for the MOF fitting.  The old one would always link objects that were in the stamp.

I think the new method is adequate for the fitting, no need to change it.

But we could run the old group finder to determine which objects should be *subtracted*. from a stamp.  Does this make sense matt?

**Comment by keckert7** [comment]
I think that plan sounds okay by me. The wide field linking length does always seem to find everything in the stamp.

**Comment by beckermr** [comment]
Yep this makes sense to me, but making the change is going to be hard in the sense that I have not touched this code in many years. @esheldon can you do this?

As a side note, we really need to not use this code base anymore. @keckert7 it would be useful to have a list of the things you are using in this repo so that @esheldon and I can figure out exactly what we want to salvage going forward.

**Comment by keckert7** [comment]
@beckermr I am using the MEDSExtractorCorrector in extractor_corrector.py, which calls in RenderNGmixNbrs, RenderNGmixNbrsFromFile from render_ngmix_nbrs.py 
I think that is all the ngmixer code that is being used for this purpose.

I think Erin is also using this code for metacal and I'm not sure if this is also what is being used for the image simulations deblending study (?).

**Comment by keckert7** [comment]
@esheldon @beckermr After examining the problem some more, I think potentially the path of least resistance (for the moment) would be for me to generate a new neighbor list defined as anything that would fall on the meds postage stamp and replace the neighbor extension in the mof file with the new one. That would avoid having to generate any new data products with mof and also make use of the current architecture we have in place for removing the neighbors.

**Comment by beckermr** [comment]
Go for it! This does indeed sound like not fighting the code we already have.
