### ISSUE TITLE
tabs are being used

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmixer#8]
There are tabs in the python files.

because python is white space significant, tabs are a bad idea unless all indentation is done with tabs.

It is generally considered bad form to use tabs in python because tabs are expanded differently in everyones editors, so the code ends up looking wrong for most people

**Comment by esheldon** [comment]
Not sure what editor you use, but usually the setting is something like "expandtabs", and we should expand them to 4 spaces to be consistent with the rest of the code

**Comment by esheldon** [comment]
(expandtabs means expand tabs to spaces)

**Comment by beckermr** [comment]
This might be how my mac has been copying things over in emacs in my terminal. In any case, this is a quick fix.

**Comment by beckermr** [comment]
fixed.
