### ISSUE TITLE
inconsistent indentation

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmixer#9]
In addition to the tabs issue, there are different indentations all over the code, even within the same function.  See for example medsio.py

**Comment by beckermr** [comment]
Really? Ohh man. I use emacs and have not been having an issue. Also the code runs fine, whereas python usually complains...

**Comment by beckermr** [comment]
Can you send me some line numbers?

**Comment by beckermr** [comment]
I just put the whole code through tabnanny. It cannot find anything after I fixed the tabs to spaces.

**Comment by beckermr** [comment]
I just ran the whole thing through reindent. The code looks fine to me. I am closing this, but feel free to reopen it. I only found two cases of weird indentation and none in medsio.py.
